physical_plan:
  graph:
    0: '8'
    1: '0'
    2: '1'
    3: '2'
    4: '3'
    5: '4'
    6: '5'
    7: '6'
    8: ''
  n_local_workers: 8
  pipes:
    0:
      name: MapperPipe_mel
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_frequency_mask
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    2:
      name: MapperPipe_time_mask
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    3:
      name: MapperPipe__stretch
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    4:
      name: MapperPipe__spec
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    5:
      name: MapperPipe__resample
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    6:
      name: MapperPipe__read
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    7:
      name: LocalFSListerPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    8:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
  