LOCAL_PARALLELISM_SCALING_FACTOR = 0.8
OFFLOAD_THRESHOLD_FRAC = 0.05
FUSED_PIPE_NAME = "FusedPipe"

RAY_SUBMIT_BATCH_SIZE = 30
RAY_AVAILABLE_PARALLELISM = 32
# RAY_SUBMIT_BATCH_SCALING_FACTOR = 2000
RAY_SUBMIT_BATCH_SCALING_FACTOR = 2000000

# Threshold at which we forbid local workers due to serialization bottlenecks
LOCAL_PARALLELISM_THRESHOLD = 100000000

SMP_AVAILABLE_PARALLELISM = 8


# Threshold for samples/s at which local parallelism is forbidden
LOCAL_PARALLELISM_SAMPLES_PER_SEC_THRESHOLD = 100
