physical_plan:
  graph:
    0: '7'
    1: '5'
    2: '0'
    3: '2'
    4: '3'
    5: '4'
    6: '1'
    7: ''
  n_local_workers: 8
  pipes:
    0:
      name: MapperPipe_to_tensor
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_distort
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    2:
      name: MapperPipe_RandomHorizontalFlip(p=1)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    3:
      name: MapperPipe_SanitizeBoundingBox(min_size=1.0, labels_getter=boxes)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    4:
      name: MapperPipe_crop
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    5:
      name: MapperPipe_zoom_out
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    6:
      name: COCOSourcePipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    7:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
