physical_plan:
  graph:
    0: '7'
    1: '3'
    2: '0'
    3: '2'
    4: '1'
    5: '4'
    6: '5'
    7: ''
  n_local_workers: 1
  pipes:
    0:
      name: MapperPipe_normalize
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    1:
      name: MapperPipe_distort
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    2:
      name: MapperPipe_random_flip
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    3:
      name: MapperPipe_resize_image
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    4:
      name: MapperPipe_distorted_bounding_box_crop
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    5:
      name: MapperPipe_read_image
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    6:
      name: COCOFileSourcePipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    7:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
