physical_plan:
  graph:
    0: '11'
    1: '0'
    2: '1'
    3: '2'
    4: '3'
    5: '4'
    6: '5'
    7: '6'
    8: '7'
    9: '8'
    10: '9'
    11: ''
  n_local_workers: 8
  pipes:
    0:
      name: BatcherPipe(batch_size=1)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_per_image_standardization
      variant: INPROCESS
    2:
      name: MapperPipe_gaussian_blur
      variant: INPROCESS
    3:
      name: MapperPipe_rgb_to_grayscale
      variant: INPROCESS
    4:
      name: MapperPipe_color_jitter
      variant: INPROCESS
    5:
      name: MapperPipe_random_flip
      variant: INPROCESS
    6:
      name: MapperPipe_crop_and_resize
      variant: INPROCESS
    7:
      name: MapperPipe_convert_to_float
      variant: INPROCESS
    8:
      name: MapperPipe_decode_jpeg
      variant: INPROCESS
    9:
      name: MapperPipe_read_file
      variant: INPROCESS
    10:
      name: LocalFSListerPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    11:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
