physical_plan:
  graph:
    0: '11'
    10: '12'
    11: ''
    12: '0'
  n_local_workers: 1
  pipes:
    0:
      name: BatcherPipe(batch_size=1)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_per_image_standardization
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    2:
      name: MapperPipe_gaussian_blur
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    3:
      name: MapperPipe_rgb_to_grayscale
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    4:
      name: MapperPipe_color_jitter
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    5:
      name: MapperPipe_random_flip
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    6:
      name: MapperPipe_crop_and_resize
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    7:
      name: MapperPipe_convert_to_float
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    8:
      name: MapperPipe_decode_jpeg
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    9:
      name: MapperPipe_read_file
      variant: TF
      variant_ctx:
        num_parallel_calls: null
        variant_type: TF
    10:
      name: LocalFSListerPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    11:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    12:
      fused_pipes:
      - 9
      - 8
      - 3
      - 6
      - 2
      - 5
      - 4
      - 7
      - 1
      name: FusedPipe
      variant: TF
      variant_ctx:
        num_parallel_calls: -1
        variant_type: TF
  