graph:
  0: '10'
  1: '0'
  2: '9'
  8: '11'
  9: '1'
  10: ''
  11: '2'
n_local_workers: 1
pipes:
  0:
    name: BatcherPipe(batch_size=1)
    variant: INPROCESS
    variant_ctx:
      variant_type: INPROCESS
  1:
    name: MapperPipe_Embedding(50257, 764)
    variant: INPROCESS
    variant_ctx:
      variant_type: INPROCESS
  2:
    name: MapperPipe_ToTensor()
    variant: INPROCESS
    variant_ctx:
      variant_type: INPROCESS
  3:
    name: MapperPipe_AddToken()
  4:
    name: MapperPipe_AddToken()
  5:
    name: "MapperPipe_VocabTransform(\n  (vocab): Vocab()\n)"
  6:
    name: MapperPipe_Truncate()
  7:
    name: MapperPipe_GPT2BPETokenizer()
  8:
    name: LocalLinePipe
    variant: INPROCESS
    variant_ctx:
      variant_type: INPROCESS
  9:
    name: ObjectDiskCachePipe
    variant: INPROCESS
    variant_ctx:
      variant_type: INPROCESS
  10:
    name: PrefetcherPipe
    variant: INPROCESS
    variant_ctx:
      variant_type: INPROCESS
  11:
    fused_pipes:
    - 7
    - 6
    - 5
    - 4
    - 3
    name: FusedPipe
    variant: RAY
    variant_ctx:
      max_inflight: 48000
      max_prefetch: 48000
      n_actors: 32
      submit_batch_size: 500
      use_threads: true
      variant_type: RAY
