physical_plan:
  graph:
    0: '10'
    1: '0'
    2: '1'
    3: '2'
    4: '3'
    5: '4'
    6: '5'
    7: '9'
    8: '7'
    9: '6'
    10: ''
  n_local_workers: 1
  pipes:
    0:
      name: BatcherPipe(batch_size=1)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_Embedding(50257, 764)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    2:
      name: MapperPipe_ToTensor()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    3:
      name: MapperPipe_AddToken()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    4:
      name: MapperPipe_AddToken()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    5:
      name: "MapperPipe_VocabTransform(\n  (vocab): Vocab()\n)"
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    6:
      name: MapperPipe_Truncate()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    7:
      name: MapperPipe_GPT2BPETokenizer()
      variant: RAY
      variant_ctx:
        max_inflight: 10000
        max_prefetch: 10000
        n_actors: 16
        submit_batch_size: 500
        use_threads: true
        variant_type: RAY
    8:
      name: LocalLinePipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    9:
      name: ObjectDiskCachePipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    10:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
