physical_plan:
  graph:
    0: '9'
    1: '0'
    2: '1'
    3: '2'
    4: '3'
    5: '4'
    6: '5'
    7: '6'
    8: '7'
    9: ''
  n_local_workers: 1
  pipes:
    0:
      name: BatcherPipe(batch_size=1)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_Embedding(50257, 764)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    2:
      name: MapperPipe_ToTensor()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    3:
      name: MapperPipe_AddToken()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    4:
      name: MapperPipe_AddToken()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    5:
      name: "MapperPipe_VocabTransform(\n  (vocab): Vocab()\n)"
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    6:
      name: MapperPipe_Truncate()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    7:
      name: MapperPipe_GPT2BPETokenizer()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    8:
      name: LocalLinePipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    9:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
  