physical_plan:
  graph:
    0: '9'
    1: '0'
    2: '1'
    8: '10'
    9: ''
    10: '2'
  n_local_workers: 1
  pipes:
    0:
      name: BatcherPipe(batch_size=1)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    1:
      name: MapperPipe_Embedding(50257, 764)
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    2:
      name: MapperPipe_ToTensor()
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    3:
      name: MapperPipe_AddToken()
      variant: INPROCESS
    4:
      name: MapperPipe_AddToken()
      variant: INPROCESS
    5:
      name: "MapperPipe_VocabTransform(\n  (vocab): Vocab()\n)"
      variant: INPROCESS
    6:
      name: MapperPipe_Truncate()
      variant: INPROCESS
    7:
      name: MapperPipe_GPT2BPETokenizer()
      variant: INPROCESS
    8:
      name: LocalLinePipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    9:
      name: PrefetcherPipe
      variant: INPROCESS
      variant_ctx:
        variant_type: INPROCESS
    10:
      fused_pipes:
      - 7
      - 6
      - 5
      - 4
      - 3
      name: FusedPipe
      variant: SMP
      variant_ctx:
        disable_torch_parallelism: true
        max_inflight: 50
        max_prefetch: 50
        n_procs: 8
        use_threads: true
        variant_type: SMP
